name: messy92-emnlp23
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blessings=1.7
  - blinker=1.6.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.05.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - cryptography=39.0.0
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - dataclasses=0.8
  - decorator=5.1.1
  - dm-tree=0.1.7
  - filelock=3.9.0
  - flatbuffers=2.0.8
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.19.1
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - h5py=3.8.0
  - hdf5=1.14.0
  - huggingface_hub=0.15.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - joblib=1.2.0
  - jpeg=9e
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - markdown=3.4.3
  - markupsafe=2.1.3
  - multidict=6.0.4
  - nccl=2.17.1.1
  - ncurses=6.3
  - numpy=1.24.3
  - nvidia-ml=7.352.0
  - oauthlib=3.2.2
  - openssl=1.1.1u
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.0.2
  - pip=23.1.2
  - platformdirs=3.5.1
  - pooch=1.7.0
  - protobuf=4.21.12
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.7.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2022.06.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - sacremoses=master
  - scipy=1.10.1
  - setuptools=67.7.2
  - six=1.16.0
  - snappy=1.1.10
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - tensorflow-gpu=2.10.0
  - tensorflow-probability=0.14.0
  - termcolor=2.3.0
  - tk=8.6.12
  - tmux=3.3
  - tokenizers=0.11.4
  - tqdm=4.65.0
  - transformers=4.28.1
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=1.26.15
  - werkzeug=2.3.4
  - wheel=0.40.0
  - wrapt=1.15.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.15.0
  - zlib=1.2.13
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - blessed==1.20.0
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - datasets==2.12.0
      - debugpy==1.6.7
      - dill==0.3.6
      - executing==1.2.0
      - fonttools==4.39.4
      - fsspec==2023.5.0
      - gpustat==1.1
      - ipykernel==6.23.1
      - ipython==8.14.0
      - jedi==0.18.2
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - multiprocess==0.70.14
      - nest-asyncio==1.5.6
      - nvidia-ml-py==11.525.112
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.0
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyzmq==25.1.0
      - responses==0.18.0
      - scikit-learn==1.2.2
      - stack-data==0.6.2
      - threadpoolctl==3.1.0
      - tornado==6.3.2
      - traitlets==5.9.0
      - wcwidth==0.2.6
      - xxhash==3.2.0
