# sentiment 데이터
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=sentiment-0 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The painting"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=sentiment-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The painting"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=sentiment-0 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The chicken"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=sentiment-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The chicken"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=sentiment-0 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The country"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=sentiment-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The country"

# # politeness 데이터
# CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=politeness-0 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="I do not know"
# CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=politeness-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="I do not know"

# # toxicity 데이터
# CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=toxicity-0 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="What"
# CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=toxicity-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="What"

# emotion 데이터
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=emotion-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="When I hear that news,"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=emotion-2 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="When I hear that news,"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=emotion-3 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="When I hear that news,"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=emotion-4 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="When I hear that news,"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=emotion-5 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="When I hear that news,"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=emotion-6 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="When I hear that news,"

# topic 데이터
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=topic-0 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The issue focused"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=topic-1 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The issue focused"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=topic-2 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The issue focused"
CUDA_VISIBLE_DEVICES=5 taskset -c 1-128 python3 main_LLM.py --my_seed=47 --task=test_eval --model=gpt2_small --dataset=topic-3 --rl_batch_size=256 --rl_lr=5e-04 --rl_num_epoch=15 --decoding=stochastic --prefix_len=2 --gen_len=15 --dropout=quantile --dropout_rate=0.95 --test_prefix="The issue focused"
